-- 게임 좋아요/싫어요 반응 (Supabase SQL Editor에서 1회 실행)
create table if not exists public.game_reactions (
  id        bigint generated by default as identity primary key,
  game_id   text not null,
  reaction  text not null check (reaction in ('like', 'dislike')),
  created_at timestamptz not null default now()
);
create index if not exists game_reactions_game_idx on public.game_reactions(game_id);

-- RLS: 클라(anon)는 insert(허용 값만) + select(카운트용)만.
alter table public.game_reactions enable row level security;
drop policy if exists gr_insert on public.game_reactions;
drop policy if exists gr_select on public.game_reactions;
create policy gr_insert on public.game_reactions
  for insert to public with check (reaction in ('like', 'dislike'));
create policy gr_select on public.game_reactions
  for select to public using (true);
