-- 뉴스 온디맨드 번역 캐시 (Supabase SQL Editor에서 1회 실행)
-- DeepL 호출 결과를 슬러그+언어별로 캐싱 — 같은 글은 최초 1회만 API 호출.
create table if not exists public.news_translations (
  id          bigint generated by default as identity primary key,
  slug        text not null,
  lang        text not null check (lang in ('en', 'ja')),
  title       text not null,
  description text,
  body_html   text not null,
  created_at  timestamptz not null default now(),
  unique (slug, lang)
);

-- RLS: 클라이언트 직접 접근 없음(서버 API 라우트만 anon 키로 읽고 씀) — 다른 공개 테이블과 동일 패턴.
alter table public.news_translations enable row level security;
drop policy if exists nt_select on public.news_translations;
drop policy if exists nt_insert on public.news_translations;
create policy nt_select on public.news_translations
  for select to public using (true);
create policy nt_insert on public.news_translations
  for insert to public with check (lang in ('en', 'ja'));
